Avoid error when piping into node
When piping bundled code into node with stdin, uvu was throwing an error here:

```js
      !!~this.has.indexOf(open) || (this.has.push(open), this.keys.push(blk));
                  ^

TypeError: this.has.indexOf is not a function
    at [stdin]:174:19
    at Timeout.exec [as _onTimeout] ([stdin]:1038:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

changing the line so that there is definitely a `this` seems to fix it.